# Generated by Django 4.1.7 on 2023-04-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuegos',
            name='anio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videojuegos',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='videojuegos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='videojuegos'),
        ),
    ]
