# Generated by Django 4.1.7 on 2023-04-11 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0003_videojuegos_anio_videojuegos_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuegos',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
